#!/bin/bash

# USAGE:
#   AWS_PROFILE=cfcommunity ./scripts/build_and_upload.sh
#
# VERSION comes from ./VERSION file
# Set any $AWS... variables to configure the aws-cli

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd $ROOT

set -eu

version=$(cat VERSION)
BUCKET=${BUCKET:-sample1-sidecar-buildpack}

echo "Building config-server-v${version}.tar.xz"

cd src/config-server-sidecar
GOOS=linux GOARCH=amd64 go build -o "config-server-v${version}" .

tar cfJ config-server-v${version}.tar.xz config-server-v${version}


echo "Uploading to s3://${BUCKET}/config-server-sidecar/"
aws s3 cp config-server-v${version}.tar.xz s3://${BUCKET}/config-server-sidecar/

sha256=$(sha256sum "config-server-v${version}.tar.xz" | awk '{print $1}')
rm config-server-v*

downloadurl="https://s3.amazonaws.com/${BUCKET}/config-server-sidecar/config-server-v${version}.tar.xz"

cd $ROOT
cat > manifest.yml <<-YAML
---
# This file is generated by scripts/build_sidecar_and_upload.sh
language: sample3-sidecar
default_versions:
- name: config-server
  version: ${version}
dependency_deprecation_dates: []

pre_package: scripts/build.sh
include_files:
  - README.md
  - VERSION
  - bin/supply
  - manifest.yml
dependencies:
- name: config-server
  version: ${version}
  uri: ${downloadurl}
  sha256: ${sha256}
  cf_stacks:
  - cflinuxfs2
  - cflinuxfs3
YAML

echo "Updated manifest.yml"
# git diff -- manifest.yml